# Base image https://hub.docker.com/u/rocker/
# docker build -f Dockerfile_singularity -t smok_soci_miss_bn_sing .
# docker image name is smok_soci_miss_bn_sing
# this is needed to construct a Docker image for the singularity image

FROM rocker/r-ver:latest

LABEL description = "Image for Socio Economic Smoking Bayesian Network analysis Project that will be used to build a singularity image to use on the HPC"
MAINTAINER "Rani Basna" ranibasna@yahoo.com

## install debian packages and the BiocManager
RUN apt-get update && apt-get install --no-install-recommends --yes r-cran-rjags

# install BiocManager for installing the graphical packages dependcies for R
RUN R -e "install.packages('BiocManager',dependencies=TRUE, repos='http://cran.rstudio.com/')"

#RUN apt-get update && apt-get install --no-install-recommends --yes r-cran-rjags\
#&& install2.r --error \
#--deps TRUE \
#BiocManager \
#&& rm -rf /tmp/downloaded_packages


## copy files
COPY R_code/Install_packages.R /Install_packages.R

## install R-packages
RUN Rscript /Install_packages.R

## install from BiocManager
RUN R -e 'BiocManager::install(c("graph", "Rgraphviz","RBGL"))'
