---
title: "R Notebook"
output:
  html_document:
    df_print: paged
---

```{r libraries}
library(targets)
```


# visualization of the missing data patterns

```{r OriginalData}
#tar_load(imput_data)
tar_load(loaded_mice_object)
data_all_miss <- loaded_mice_object$data # this is the missing original data
```


```{r}
p_missing_df <- unlist(lapply(data_all_miss, function(x) sum(is.na(x))))/nrow(data_all_miss)
sort(p_missing_df[p_missing_df > 0], decreasing = TRUE)
```
```{r}
vis_miss(data_all_miss, warn_large_data = FALSE)
```

```{r}
gg_miss_upset(data_all_miss)
```

```{r}
# missing cases
gg_miss_case(data_all_miss)
```

```{r}
gg_miss_fct(x = data_all_miss, fct = sei_class)
```

```{r}
gg_miss_fct(x = data_all_miss, fct = trt_diabetes)
```

<!-- ```{r} -->
<!-- explanatory =  c("asthma_treatmnt","e_amount", "age_group", "poll_exp", "varq10b","smoke_expwork") -->
<!-- dependent = "asthma" -->
<!-- data_all %>%  missing_pairs(dependent, explanatory) -->
<!-- ``` -->

```{r}
# explanatory =  c("e_amount","BMI")
# data_all$s_amount
# explanatory =  c("sei_class","education")
# explanatory =  c("sei_class","vars_status")
# explanatory =  c("education","s_amount")

#explanatory =  c("education", "syk_class", "BMI")
explanatory =  c("education", "sei_class", "BMI")
dependent = "c_asthma"
data_all_miss %>%  missing_pairs(dependent, explanatory)
```


```{r}
ggplot(data_all_miss, aes(x = duration, y = BMI)) + geom_miss_point()
```

```{r}
ggplot(data_all_miss, aes(x = duration, y = BMI)) + geom_miss_point() + facet_wrap(~education)
```



<!-- # visualization after imputation -->

<!-- ```{r} -->
<!-- #tar_load(density_plot) -->
<!-- #density_plot -->
<!-- ``` -->

<!-- ```{r} -->
<!-- stripplot(loaded_mice_object, pch = 20, cex = 1.2) -->
<!-- ``` -->

<!-- ```{r} -->
<!-- df_1 <- data_all_miss %>% select(c(BMI, duration)) %>% rename(varduration_imp = duration) %>% -->
<!--   mutate(varduration_imp = as.logical(ifelse(is.na(varduration_imp),"TRUE","FALSE"))) %>% rownames_to_column() -->
<!-- # SELECT A SPECIFIC SAMPLE -->
<!-- imp_data <- complete(loaded_mice_object, 1) -->
<!-- df_2 <- imp_data %>% select(duration, BMI) %>% rownames_to_column() -->
<!-- df <- left_join(df_1,df_2) -->
<!-- df <- as.data.frame(df) -->
<!-- vars <- c("BMI","duration","varduration_imp") -->
<!-- VIM::marginplot(df[,vars], delimiter="imp", alpha=0.6, pch=c(19)) -->
<!-- ``` -->


<!-- ```{r} -->
<!-- df_1 <- data_all_miss %>% select(c(BMI, age)) %>% rename(BMI_imp = BMI) %>% -->
<!--   mutate(BMI_imp = as.logical(ifelse(is.na(BMI_imp),"TRUE","FALSE"))) %>% rownames_to_column() -->
<!-- df_2 <- imp_data %>% select(age, BMI) %>% rownames_to_column() -->
<!-- df <- left_join(df_1,df_2) -->

<!-- df <- as.data.frame(df) -->
<!-- vars <- c("age", "BMI","BMI_imp") -->
<!-- marginplot(df[,vars], delimiter="imp", alpha=0.6, pch=c(19)) -->
<!-- ``` -->


<!-- ```{r} -->
<!-- df_3 <- data_all_miss %>% select(c(duration, BMI)) %>% rename(BMI_imp = BMI, duration_imp = duration) %>% mutate(BMI_imp = as.logical(ifelse(is.na(BMI_imp),"TRUE","FALSE"))) %>% mutate(duration_imp = as.logical(ifelse(is.na(duration_imp),"TRUE","FALSE"))) %>% rownames_to_column() -->

<!-- df_4 <- imp_data %>% select(duration, BMI) %>% rownames_to_column() -->
<!-- df <- left_join(df_3,df_4) -->

<!-- df <- as.data.frame(df) -->
<!-- #vars <- c("BMI","duration","BMI_imp") -->
<!-- vars <- c("BMI","duration","duration_imp") -->
<!-- #vars <- c("duration","BMI","duration_imp") -->
<!-- # imputting values in sleep dataset using knn -->
<!-- histMiss(df[,vars], delimiter="imp", selection="any") -->
<!-- ``` -->

<!-- ```{r} -->
<!-- pbox(df[,vars], delimiter="imp", pch=c(19)) -->
<!-- pbox(df[,vars], delimiter="imp", selection = "none") -->
<!-- pbox(df[,vars], delimiter="imp", selection = "all") -->
<!-- ``` -->


<!-- ```{r} -->
<!-- #cat_var <- sei_class -->
<!-- df_1 <- data_all_miss %>% select(c(BMI, sei_class)) %>% rename(sei_class_imp = sei_class) %>% -->
<!--   mutate(sei_class_imp = as.logical(ifelse(is.na(sei_class_imp),"TRUE","FALSE"))) %>% rownames_to_column() -->

<!-- df_2 <- imp_data %>% select(sei_class, BMI) %>% rownames_to_column() -->

<!-- df <- left_join(df_1,df_2) -->
<!-- df <- as.data.frame(df) -->
<!-- vars <- c("BMI","sei_class","sei_class_imp") -->
<!-- barMiss(df[,vars], delimiter = "_imp", selection = "any", only.miss = FALSE) -->
<!-- ## -->
<!-- df_1 <- data_all_miss %>% select(c(BMI, syk_class)) %>% rename(syk_class_imp = syk_class) %>% -->
<!--   mutate(syk_class_imp = as.logical(ifelse(is.na(syk_class_imp),"TRUE","FALSE"))) %>% rownames_to_column() -->
<!-- df_2 <- imp_data %>% select(syk_class, BMI) %>% rownames_to_column() -->
<!-- df <- left_join(df_1,df_2) -->
<!-- df <- as.data.frame(df) -->
<!-- vars <- c("BMI","syk_class","syk_class_imp") -->
<!-- barMiss(df[,vars], delimiter = "_imp", selection = "any", only.miss = FALSE) -->
<!-- ``` -->


<!-- ```{r} -->
<!-- # matrixplot(df[,vars], delimiter="_imp", sortby="gender") -->
<!-- matrixplot(df[,vars], delimiter="_imp", sortby="syk_class") -->
<!-- ``` -->


